### ISSUE TITLE
Code crash / forgot to push? 

### ISSUE THREAD

**Issue by senden9** [fasterthanlime/axact#1]
Hi!

I know that this is only a demo-demo repo for the YouTube video but I want to report that anyways. Feel free to ignore.

When starting the code from commit 3cf751345bfc003bc0616d33c43d7c08d3d61dd9 on my Ubuntu 22.10 machine I get a panic because of unwrapping in line https://github.com/fasterthanlime/axact/blob/3cf751345bfc003bc0616d33c43d7c08d3d61dd9/src/main.rs#L37.

Here is the backtrace:
```
$ RUST_BACKTRACE=1 RUST_LOG=debug cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/axact`
Listening on 0.0.0.0:7032
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])', src/main.rs:37:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: axact::main::{{closure}}::{{closure}}
             at ./src/main.rs:37:13
   5: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
   6: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
   7: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
   8: tokio::runtime::task::core::Core<T,S>::poll
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
   9: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panic/unwind_safe.rs:271:9
  11: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  12: __rust_try
  13: std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  14: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  15: tokio::runtime::task::harness::poll_future
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  16: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  17: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  18: tokio::runtime::task::raw::poll
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  19: tokio::runtime::task::raw::RawTask::poll
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  20: tokio::runtime::task::UnownedTask<S>::run
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
  21: tokio::runtime::blocking::pool::Task::run
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
  22: tokio::runtime::blocking::pool::Inner::run
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
  23: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I saw that in the video at https://youtu.be/c_5Jy_AVDaM?t=2970. In the video you just ignored the result instead of unwrapping. Maybe you just forget a `git push`?

**Comment by fasterthanlime** [comment]
> Maybe you just forget a `git push`?

Absolutely! It's fixed now.
